<a href="https://colab.research.google.com/github/Dharshan4038/NLP/blob/main/Fake_News_Classifier_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [18]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv')

In [4]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
df = df.dropna()

In [6]:
X = df.drop('label',axis=1)
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [7]:
y = df['label']
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [8]:
X.shape

(18285, 4)

In [9]:
y.shape

(18285,)

In [10]:
import tensorflow

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
messages = X.copy()

In [13]:
messages.reset_index(inplace = True)

In [14]:
import nltk
import re
from nltk.corpus import stopwords

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [16]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [21]:
from nltk import WordNetLemmatizer
wnl = WordNetLemmatizer()
corpus = []
for i in range(len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['text'][i])
  review = review.lower()
  review = review.split()
  review = [wnl.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [22]:
# @title Default title text
import tensorflow as tf
device_name = tf.test.gpu_device_name()


In [23]:
device_name

'/device:GPU:0'

In [27]:
corpus[0]

'house dem aide even see comey letter jason chaffetz tweeted darrell lucus october subscribe jason chaffetz stump american fork utah image courtesy michael jolley available creative common license apology keith olbermann doubt worst person world week fbi director james comey according house democratic aide look like also know second worst person well turn comey sent infamous letter announcing fbi looking email may related hillary clinton email server ranking democrat relevant committee hear comey found via tweet one republican committee chairman know comey notified republican chairman democratic ranking member house intelligence judiciary oversight committee agency reviewing email recently discovered order see contained classified information long letter went oversight committee chairman jason chaffetz set political world ablaze tweet fbi dir informed fbi learned existence email appear pertinent investigation case reopened jason chaffetz jasoninthehouse october course know case comey a

In [29]:
vocab_size = 5000
one_hot_rep = [one_hot(words,vocab_size) for words in corpus]
one_hot_rep[0]

[2027,
 25,
 4922,
 3498,
 4190,
 2339,
 3124,
 2924,
 1760,
 2580,
 2063,
 335,
 136,
 2007,
 2924,
 1760,
 737,
 1624,
 374,
 1393,
 2851,
 4916,
 4573,
 3326,
 3842,
 3894,
 3663,
 4681,
 3842,
 2032,
 386,
 1269,
 4094,
 1677,
 1516,
 269,
 2202,
 3189,
 276,
 2339,
 1286,
 2027,
 158,
 4922,
 4576,
 4454,
 743,
 2830,
 286,
 4094,
 1677,
 3239,
 4374,
 2339,
 4784,
 1926,
 3124,
 1257,
 2202,
 672,
 1853,
 3260,
 2936,
 185,
 489,
 1853,
 1218,
 1334,
 1285,
 3752,
 2918,
 4692,
 2339,
 4855,
 4498,
 3444,
 3498,
 1873,
 2918,
 3923,
 2830,
 2339,
 1136,
 1873,
 3923,
 158,
 1334,
 489,
 2027,
 3530,
 444,
 2771,
 2918,
 4654,
 2827,
 1853,
 4230,
 3211,
 522,
 4190,
 2093,
 896,
 1834,
 2913,
 3124,
 1340,
 2771,
 2918,
 3923,
 2924,
 1760,
 583,
 4338,
 1516,
 4949,
 3444,
 2202,
 4947,
 2658,
 2202,
 4833,
 628,
 1853,
 2651,
 3800,
 2575,
 772,
 445,
 2924,
 1760,
 3425,
 136,
 645,
 2830,
 772,
 2339,
 1548,
 4990,
 2827,
 1853,
 4828,
 3485,
 772,
 2830,
 597,
 4232,
 892,
 

In [33]:
sent_len = 50
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[  88 1129  184 ... 2140  936 4347]
 [4299 2509 1792 ... 4143  596 2158]
 [2335 2260  798 ... 2948 3065 4218]
 ...
 [ 277 3976 1958 ... 2351 4027 3152]
 [3830 4655 2952 ... 2669 3921 1675]
 [2716 4868 2652 ... 1020  885 4241]]


In [34]:
embedded_docs[0]

array([  88, 1129,  184, 4272, 1112, 2933,  372, 4374,  489, 1743,  916,
       3473, 4508, 2495, 1743,  916, 4094, 1391, 1527,  389, 1038, 1206,
       2441, 1228, 2591, 1616, 2040, 3077,  487,  726, 2487, 4719, 3260,
       2830,   53,  246,  389,   25, 3904, 4364, 1680,  690, 4347, 1106,
       1515, 1963, 2063, 2140,  936, 4347], dtype=int32)

In [45]:
from tensorflow.keras.layers import Dropout

In [46]:
#creating model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(vocab_size,embedding_vector_features,input_length=sent_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 50, 40)            0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [47]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [48]:
X_final.shape,y_final.shape

((18285, 50), (18285,))

In [49]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.33,random_state=0)

In [50]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 16s 69ms/step - loss: 0.3916 - accuracy: 0.8157 - val_loss: 0.2778 - val_accuracy: 0.8830
Epoch 2/10
192/192 [==============================] - 6s 29ms/step - loss: 0.2101 - accuracy: 0.9171 - val_loss: 0.2658 - val_accuracy: 0.8858
Epoch 3/10
192/192 [==============================] - 4s 22ms/step - loss: 0.1547 - accuracy: 0.9433 - val_loss: 0.2983 - val_accuracy: 0.8804
Epoch 4/10
192/192 [==============================] - 3s 14ms/step - loss: 0.1239 - accuracy: 0.9551 - val_loss: 0.3045 - val_accuracy: 0.8789
Epoch 5/10
192/192 [==============================] - 2s 13ms/step - loss: 0.0958 - accuracy: 0.9691 - val_loss: 0.3508 - val_accuracy: 0.8767
Epoch 6/10
192/192 [==============================] - 3s 17ms/step - loss: 0.0701 - accuracy: 0.9757 - val_loss: 0.4007 - val_accuracy: 0.8737
Epoch 7/10
192/192 [==============================] - 3s 13ms/step - loss: 0.0573 - accuracy: 0.9819 - val_loss: 0.3899 - val_accuracy: 0.877

In [51]:
y_pred = model.predict(X_test)

189/189 [==============================] - 1s 3ms/step


In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
confusion_matrix(y_test,y_pred.round())

array([[2996,  393],
       [ 371, 2275]])

In [54]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred.round())

0.8734051367025684